
# Current Data:



import csv
import random

# Define your list of variables and their properties
variables = [
    ("variable_1", None, 10),  # This variable has a fixed value of 10
    ("variable_2", 2, 3),  # This variable has a normal distribution with mean 2 and standard deviation 3
    ("variable_3", lambda: random.uniform(5, 15)),  # This variable is generated by a random function
    ("variable_4", None, 0.2),  # This variable has a fixed value of 0.2
]

# Open the CSV file in write mode
with open("output.csv", "w") as csvfile:
    writer = csv.writer(csvfile)

    # Write the header row
    writer.writerow(["Variable", "Value"])

    # Iterate through each variable and write its value to the CSV file
    for name, distribution, sd in variables:
        if distribution is None:
            value = distribution
        elif callable(distribution):
            value = distribution()
        else:
            value = random.normalvariate(distribution, sd)
        writer.writerow([name, value])

print("CSV file 'output.csv' generated successfully!")
